[project]
name = "api-consesionaria-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joaquin-CasVar", email = "j.castellanovarela@itecriocuarto.org.ar" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
]

[project.scripts]
api-consesionaria-django = "api_consesionaria_django:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
