# Generated by Django 6.1 on 2026-08-26 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'colores',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipo de combustible',
                'verbose_name_plural': 'tipos de combustible',
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipo de direccion',
                'verbose_name_plural': 'tipos de direccion',
            },
        ),
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipo de transmision',
                'verbose_name_plural': 'tipos de transmision',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('turbo', models.BooleanField(default=False)),
                ('anio', models.IntegerField()),
                ('nuevo', models.BooleanField(default=True)),
                ('kilometros', models.IntegerField(default=0)),
                ('patente', models.CharField(blank=True, max_length=20, null=True)),
                ('puertas', models.IntegerField(default=4)),
                ('marchas', models.IntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.marca')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipocombustible')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipodireccion')),
                ('transmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipotransmision')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
